### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by pcasaretto** [pcasaretto/atom-tabularize#15]
Activating tabularize on this
```
var demo = {
  object: {
    attribute: "value"
  }
}
```
using `:` as the separator causes
```
Uncaught TypeError: Cannot read property 'length' of null /Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focu…:1172
(anonymous function) /Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focu…:1172
(anonymous function) /Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focu…:277
_.each._.forEach /Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focu…:103
_.max /Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focu…:276
_.zip /Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focu…:564
_.(anonymous function) /Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focu…:1371
(anonymous function) tabularize.coffee:46_.map._.collect /Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focu…:124
_.(anonymous function) /Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focu…:1371
(anonymous function) tabularize.coffee:
42(anonymous function) /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:756
module.exports.History.transact /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:90
module.exports.TextBuffer.transact /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:633
module.exports.TextEditor.transact /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1125
module.exports.TextEditor.mutateSelectedText /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:749
module.exports.Tabularize.tabularize tabularize.coffee:15
module.exports.TabularizeView.confirm tabularize-view.coffee:53
(anonymous function) tabularize-view.coffee:25
```

**Comment by boriscy** [comment]
Again,I have version 0.2.3

/usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:124
Hide Stack Trace
TypeError: Cannot read property 'length' of null
    at Function.module.exports.Tabularize.leftAlign (/home/boris/.atom/packages/tabularize/lib/tabularize.coffee:63:35)
    at Function.module.exports.Tabularize.paddingColumn (/home/boris/.atom/packages/tabularize/lib/tabularize.coffee:92:34)
    at /home/boris/.atom/packages/tabularize/lib/tabularize.coffee:38:38
    at /home/boris/.atom/packages/tabularize/lib/tabularize.coffee:41:11
    at /usr/share/atom/resources/app/src/text-editor.js:841:29
    at History.module.exports.History.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:115:18)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1215:26)
    at /usr/share/atom/resources/app/src/text-editor.js:835:24
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:2155:18)

**Comment by lazutkin** [comment]
And again

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tabularize](https://github.com/pcasaretto/atom-tabularize) package, v0.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:128

TypeError: Cannot read property 'length' of null
  at Function.module.exports.Tabularize.leftAlign (/Users/dimka/.atom/packages/tabularize/lib/tabularize.coffee:56:35)
  at Function.module.exports.Tabularize.paddingColumn (/Users/dimka/.atom/packages/tabularize/lib/tabularize.coffee:78:19)
  at /Users/dimka/.atom/packages/tabularize/lib/tabularize.coffee:35:38
  at /Users/dimka/.atom/packages/tabularize/lib/tabularize.coffee:41:11
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:758:29
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:119:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:647:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1107:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:752:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1925:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1899:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:750:19)
  at Function.module.exports.Tabularize.tabularize (/Users/dimka/.atom/packages/tabularize/lib/tabularize.coffee:17:14)
  at TabularizeView.module.exports.TabularizeView.confirm (/Users/dimka/.atom/packages/tabularize/lib/tabularize-view.coffee:54:16)
  at atom-text-editor.<anonymous> (/Users/dimka/.atom/packages/tabularize/lib/tabularize-view.coffee:30:64)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:37.8.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
  3x -0:37.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:29.4.0 command-palette:toggle (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:29.3.0 blur (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:26.9.0 core:confirm (atom-text-editor.editor.mini)
     -0:26.9.0 blur (atom-text-editor.editor.mini)
     -0:26.9.0 tabularize:toggle (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
  4x -0:26.9.0 blur (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:14.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:14.6.0 blur (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:05.1.0 core:confirm (atom-text-editor.editor.mini)
     -0:05.1.0 blur (atom-text-editor.editor.mini)
     -0:05.1.0 tabularize:toggle (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:05.1.0 blur (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:00.4.0 core:confirm (atom-text-editor.editor.mini)
  3x -0:00.4.0 blur (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "projectHome": "~/Projects"
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.0.7
autocomplete-plus, v2.12.0
linter, v0.12.1
linter-tslint, v0.2.1
tabularize, v0.2.3
vim-mode, v0.44.0

# Dev
No dev packages
```

**Comment by guih** [comment]
@pcasaretto I guess this is related to columns size.
Selecting the text until last `,` in the block: 
```
{
  "foo" : 1,
  "large_row" : 2,
  "small" : 3,
}
```
throws this error but if I add blank spaces at the end of third row until it reaches the column of the largest row or if I put the largest row at the end, the error does not happens

I Guess the fix is in this line, https://github.com/pcasaretto/atom-tabularize/blob/master/lib/tabularize.coffee#L12

**Comment by lazutkin** [comment]
:+1:

**Comment by bronson** [comment]
Huh, first attempt at tabularizing and I hit this bug.

Here's the text:

```
  background-color: inherit;
  border: none;
  width: 100%;
  font-weight: normal;
  color: @text-color;
  line-height: 1.28;
  cursor: default;
  white-space: nowrap;
  padding-left: 10px;
```

Hoping it gets addressed!

**Comment by bronson** [comment]
Second attempt dies with the same bug.  0 for 2, guess it's time to uninstall.  Does this plugin work for anyone?

Here's the text, tabularizing on `|`.

```
lakdjgas|lkjf|aldjkf
alksdgj|asdlgkj|lasdkgj
```

**Comment by pcasaretto** [comment]
Sorry @bronson , I've been neglecting this guy.
It does work on most occasions.
I'll try to fix this ASAP.

**Comment by bronson** [comment]
No worries, I'll definitely try it again when there's progress.

**Comment by jonathanmcelroy** [comment]
1. Use vim mode.
2. Enter this text:
```
    test1 = "a"
    test11 = "b"
    test111 = "c"
    test1111 = "d"
```
3. Select the paragraph by entering "vip" or by placing the cursor on the top line and entering "Vjjj" or by placing the cursor on the bottom line and entering "Vkkk".
4. Run tabularize on "=".

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [tabularize](https://github.com/pcasaretto/atom-tabularize) package, v0.2.4

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At C:\Users\jmcelroy\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:745

TypeError: Cannot read property 'length' of null
    at Function.module.exports.Tabularize.leftAlign (C:\Users\jmcelroy\.atom\packages\tabularize\lib\tabularize.coffee:63:35)
    at Function.module.exports.Tabularize.paddingColumn (C:\Users\jmcelroy\.atom\packages\tabularize\lib\tabularize.coffee:92:34)
    at C:\Users\jmcelroy\.atom\packages\tabularize\lib\tabularize.coffee:38:38
    at C:\Users\jmcelroy\.atom\packages\tabularize\lib\tabularize.coffee:41:11
    at C:\Users\jmcelroy\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:778:29
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\jmcelroy\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:740:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\jmcelroy\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:1151:26)
    at C:\Users\jmcelroy\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:772:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\jmcelroy\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:2017:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\jmcelroy\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:1987:35)
```

### Commands

```
     -1:18.9.0 application:add-project-folder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:09.0 application:open-file (atom-pane.pane.active)
     -1:01.2.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 12x -0:58.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:56.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:56.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:56 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:53.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:50.4.0 editor:fold-all (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:10.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:09.7.0 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:09.3.0 vim-mode:select-inside-paragraph (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:08.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:06.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.7.0 tabularize:toggle (atom-text-editor.editor.vim-mode.visual-mode)
     -0:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

I also noticed that if all the lines but the last are selected, it will align everything in the paragraph as if the whole paragraph was selected.

**Comment by bronson** [comment]
Yes!  I'm running vim-mode too.  I should have figured it would be a plugin conflict.

**Comment by pcasaretto** [comment]
I do not believe it's a conflict. Tabularize works with selections, it doesn't matter where they come from.
@guih seems to have nailed down the problem.
But I'll be sure to make test cases out the examples you guys gave and fix this damn bug.
Thanks for reporting!

**Comment by pcasaretto** [comment]
Could you guys please test v0.2.5 ?

**Comment by bronson** [comment]
Yes!  No crash.  Very nice.

**Comment by bronson** [comment]
When I select only these two lines:

``` ruby
  app = "property-#{Rails.env}"
  puts "restarting #{app}"
```

and tabularize:toggle on `"` (or `\"`, doesn't matter), I get:

``` ruby
  app =                                            " property-#{Rails.env} "
  puts                                             " restarting #{app}     "
```

I would have expected:

``` ruby
  app = " property-#{Rails.env} "
  puts  " restarting #{app} "
```

Am I missing something here?

Some other tabularizations have worked great.  Nice work!

**Comment by pcasaretto** [comment]
Weird, I've got exactly what you expected. Can you restart atom (you probably already have) and test it again?

**Comment by bronson** [comment]
I think I get it...  If I triple-click to select lines downwards, it happens.  If I linewise select moving upwards, it doesn't.  Since the following line has no `"` in it, I guess it's just bouncing the table out to the end of that line.

![bug3](https://cloud.githubusercontent.com/assets/1776/8881834/a6f0e770-31f7-11e5-8355-84b40dedfea0.gif)

Seems to me like the line following the selection shouldn't be included in the computation?  Happy to open a new issue if you think this is worth reporting.

**Comment by bronson** [comment]
In the gif I'm using vim-mode's V selection, which is implemented the same as triple-click...  Both show the same behavior.  I just didn't want to re-record the video :)

**Comment by pcasaretto** [comment]
Please do open that issue!
