### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /?/: Nothing to repeat

### ISSUE THREAD

**Issue by oknixus** [pcasaretto/atom-tabularize#23]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Unknown Windows Version
**Thrown From**: [tabularize](https://github.com/pcasaretto/atom-tabularize) package, v0.2.5
### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /?/: Nothing to repeat

```
At C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:756

SyntaxError: Invalid regular expression: /?/: Nothing to repeat
  at new RegExp (native)
  at RegExp (native)
  at C:\Users\KJRS-Nixus\.atom\packages\tabularize\lib\tabularize.coffee:18:27
  at C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\src\text-editor.js:778:29
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:751:18)
  at TextEditor.module.exports.TextEditor.transact (C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\src\text-editor.js:1151:26)
  at C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\src\text-editor.js:772:24
  at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\src\text-editor.js:2017:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\src\text-editor.js:1987:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\src\text-editor.js:770:19)
  at Function.module.exports.Tabularize.tabularize (C:\Users\KJRS-Nixus\.atom\packages\tabularize\lib\tabularize.coffee:17:14)
  at TabularizeView.module.exports.TabularizeView.confirm (C:\Users\KJRS-Nixus\.atom\packages\tabularize\lib\tabularize-view.coffee:54:16)
  at atom-text-editor.<anonymous> (C:\Users\KJRS-Nixus\.atom\packages\tabularize\lib\tabularize-view.coffee:30:64)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\KJRS-Nixus\AppData\Local\atom\app-1.0.3\resources\app.asar\src\window-event-handler.js:177:20)

```
### Commands

```
     -0:10.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:10.5.0 vim-mode-visual-block:j (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:10.5.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:10.3.0 vim-mode-visual-block:j (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:10.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:09.9.0 vim-mode-visual-block:j (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:09.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:08.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:08.4.0 blur (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:06.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:06.4.0 tabularize:toggle (atom-text-editor.editor.vim-mode.visual-mode)
     -0:06.4.0 blur (atom-text-editor.editor.vim-mode.visual-mode)
     -0:04.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:04.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:00.4.0 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "php-analyser"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-php, v0.3.6
linter, vundefined
linter-php, v1.0.2
linter-phpmd, v1.0.0
tabularize, v0.2.5
vim-mode, v0.57.0
vim-mode-visual-block, v0.2.13

# Dev
No dev packages
```

**Comment by pcasaretto** [comment]
你好 NixusCN, this package expects a regex. Try using `\?`.
The package should make that clearer. In fact, it should not allow the command to run if there are no matches.
Related to #16

**Comment by oknixus** [comment]
Thanks.:)
