### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /*)/: Nothing to repeat

### ISSUE THREAD

**Issue by dschnee** [pcasaretto/atom-tabularize#26]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0-beta1
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [tabularize](https://github.com/pcasaretto/atom-tabularize) package, v0.2.5
### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /*)/: Nothing to repeat

```
At C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:770

SyntaxError: Invalid regular expression: /*)/: Nothing to repeat
  at new RegExp (native)
  at RegExp (native)
  at C:\Users\David\.atom\packages\tabularize\lib\tabularize.coffee:18:27
  at C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\text-editor.js:719:29
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:765:18)
  at TextEditor.module.exports.TextEditor.transact (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\text-editor.js:1100:26)
  at C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\text-editor.js:713:24
  at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\text-editor.js:1964:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\text-editor.js:1926:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\text-editor.js:711:19)
  at Function.module.exports.Tabularize.tabularize (C:\Users\David\.atom\packages\tabularize\lib\tabularize.coffee:17:14)
  at TabularizeView.module.exports.TabularizeView.confirm (C:\Users\David\.atom\packages\tabularize\lib\tabularize-view.coffee:54:16)
  at atom-text-editor.<anonymous> (C:\Users\David\.atom\packages\tabularize\lib\tabularize-view.coffee:30:64)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\command-registry.js:243:29)
  at C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\window-event-handler.js:97:20)

```
### Commands

```
     -9:41.1.0 command-palette:toggle (atom-text-editor.editor)
  7x -4:53.7.0 window:toggle-full-screen (atom-text-editor.editor.is-focused)
  2x -2:26.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:49.7.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:19.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:05.2.0 tabularize:toggle (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autohide-tree-view",
      "webbox-color",
      "wrap-guide",
      "vim-mode",
      "multi-wrap-guide",
      "project-manager",
      "merge-conflicts",
      "tree-view-breadcrumb",
      "symbols-tree-view",
      "fancy-bracket-matcher",
      "letter-spacing"
    ],
    "openEmptyEditorOnStart": false,
    "excludeVcsIgnoredPaths": false,
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "visual-studio-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
copy-filename, v1.0.1
documentation-renderer, v0.2.1
file-icons, v1.6.11
fonts, v0.7.0
goto-mathematica, v0.1.0
hex, v0.6.2
language-mathematica, v0.1.0
linter, v1.9.1
linter-chktex, v1.2.0
linter-gcc, v0.3.8
linter-js-standard, v3.2.1
linter-matlab, v1.0.0
linter-tidy, v1.0.1
minimap, v4.15.0
minimap-find-and-replace, v4.3.1
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
neon-cursor, v0.2.0
pdf-view, v0.34.0
pigments, v0.18.0
project-view, v0.1.2
Sublime-Style-Column-Selection, v1.3.0
sync-settings, v0.6.0
tabs-to-spaces, v0.11.1
tabularize, v0.2.5
terminal-plus, v0.12.2
terminal-status, v1.6.8
tool-bar, v0.1.9
toolbar-iconshortcuts, v1.0.0
trailing-spaces, v0.3.2
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
visual-studio-dark-syntax, v0.1.0

# Dev
No dev packages
```

**Comment by pcasaretto** [comment]
Hey :)

Although it is not clear, you have to input a regular expression.
Try `\*\(`
